# Web容器配置
server:
  port: 8082

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int(10000,19999)}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  httpclient:
    enabled: true

hystrix:
  command:
    default:
      execution:
        # Global Hystrix timeout(ms)
        isolation.thread.timeoutInMilliseconds: 30000
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 100
      queueSizeRejectionThreshold: 5

beetl:
  templatesPath: templates

# actuator 安全性配置
security:
  basic:
    enabled:  true
    path: /admin
  user:
    name: admin
    password: admin